- Counterfeit Monkey.inform/Source/story.ni
This inserts a missing paragraph break between "None of that is in the backpack" and the command prompt when the former line is the last of the inventory listing. 
(It will be the last line if the player is not wearing anything and carrying an empty backpack.)
> Minor inventory listing adjustment

- Counterfeit Monkey Materials/Extensions/Dannii Willis/Ultra Undo.i7x
- Counterfeit Monkey.inform/Source/story.ni
Maybe this isn't much of an improvement, but it has a couple of advantages. Instead of incrementing the filename of each new undo file, it rolls back to 1 when it goes past the ULTRA_UNDO_MAX_COUNT (default 10). This limits the number of files that might get left behind, and makes it easy to delete all of them.
Now all undo files are removed whenever the Ultra_Undo_Test fails. I'm not sure if that is the best place to do this or whether it is even necessary.
Please take a look and let me know what you think.
> Change Ultra Undo to limit the number of possible undo filenames.

- Counterfeit Monkey.inform/Source/story.ni
Two bugs: 
If you try to put the backpack into itself, the game will open the backpack before telling you that you can't.
If you try to put something into to backpack that already is in there, the game will open the backpack, take out the thing and then put it back in.
I made a couple of sanity checks to prevent those.
> Prevent some unwanted implicit actions.

- Counterfeit Monkey.inform/Source/story.ni
For some reason there was an extra line break printed after the initial mention of the jotter ("A jotter is propped up next to the projector") in the projection booth.
> Fix a double line break after the initial description of the jotter.

- Counterfeit Monkey.inform/Source/story.ni
Fixes several bugs and oddities in the utilitarian inventory style listing, at the cost of increased complexity. Hopefully this won't be noticeably slower than before. No doubt some of those conditional line breaks could be combined or replaced with paragraph breaks.
The [is-are] substitution is not working as expected.
> Various fixes to utilitarian inventory listing.

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
Sometimes you would try to drop yourself while dropping all. This was caused by the code that removes the "What do you want to drop those things in?" message that appears when you type DROP ALL while carrying nothing.
> Remove yourself from drop all-lists

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act V Atlantida Herself.i7x
Otherwise there will be an ugly list if we drop everything while out at sea, as seen in the TEST HARD transcript. This reverts commit [42fbdfe](https://github.com/i7/counterfeit-monkey/commit/42fbdfe9833201a0678c1cf9ad705a8fb5c99791).
> Hide contents of kayak.

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
This improves some of the facing messages that are printed when you look or try to walk in a direction where there is no exit.
It changes confusing stuff like
```
>s
There is nothing of note to the southeast, but to the southwest is Webster Court.
We can go southwest to Webster Court from here.
```
to the somewhat less confusing
```
>s
There is nothing of note to the south or the southeast, but to the southwest is Webster Court.
We can go southwest to Webster Court from here.
```
> Make the facing output nicer.

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act III Among Scholars.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tools.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
As discussed in #27, here are some new grammar lines that use [thing] instead of [something] in order for the parser to consider them before grammar lines with [any locally-present room].
> Give actions applying to things precedence over actions applying to rooms.

- Counterfeit Monkey.inform/Source/story.ni
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tests.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/actions on multiple objects.i7x
Even more than #44 this is a lot of code (and work) to avoid a rather minor annoyance. 
This game allows the use of multiple objects with five actions (I think): take all, drop all, get all from, put all on and insert all in. 
In particular the last two would originally cause really long lists of "x-remover: Putting things on the marble fountain would achieve nothing" and so on, sometimes over a hundred lines long. As a player, you feel that printing that message once would have been enough. So I've gone to some lengths to accomplish exactly that. If you're not actually allowed to put all your stuff in a container or on a supporter, this tries to reduce the list to a single error message, either the same custom message that you get when carrying out the action with a single object, or …
> Shorter multiple-objects action lists

- Counterfeit Monkey.inform/Source/story.ni
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act I Among Sightseers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act II Among Smugglers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act III Among Scholars.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act IV Among Policemen.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act V Atlantida Herself.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tests.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/insides and outsides.i7x
In the original code the standard Inform INSIDE and OUTSIDE directions are only used in the traffic circle, but they can be tried anywhere, with responses such as "That way is the corner of Sigil Street and Sigil Street" or "To the outside the Church Forecourt meets the Church Forecourt". There is also a leave [any room] command that will take us out the only exit in dead end rooms.
In the Cinema Lobby there is a check to take you west if you type GO INSIDE, and I found I wanted to add more and more of these: one that would go east if typing GO INSIDE outside the hostel and so on. So I figured I might as well add them all at once.
This PR implements IN and OUT as valid directions wherever deemed appropriate. I was worried that adding the standard inside and outside directions would …
> Going in and going out, looking in and looking out

- Counterfeit Monkey.inform/Source/story.ni
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act I Among Sightseers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act IV Among Policemen.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act V Atlantida Herself.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Liquids.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tests.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tools.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/actions on multiple objects.i7x
This is some improved behavior of fluid things, sinks, taps and washing. I've tried to stay true the spirit of this original comment at the beginning of the liquids section:
> We could have used a full-bore liquid extension, but there's really no reason to do so: the player is not going to be allowed to mix liquids or have partial liquid quantities, and in fact we want to encourage him to think of all objects in the game universe as atomic rather than partial and divisible.
However, I've also tried to aid the suspension of disbelief a little. It is no longer allowed to put things in sinks or showers or other things with drains and faucets, nor to pick up uncontained fluid things and put them in containers or on supporters. I don't know if this was ever deliberately possible before, and I …
> Liquid behavior

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act I Among Sightseers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tests.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
Give the same complaint about not having the backpack or the plans when we try to leave the starting area, even if we try to GO TO MONUMENT GREEN or anything else that looks interesting on the map.
There are a couple of other situations where the game stops us at a particular room with a refusal message, while not giving the same message when trying to go to the rooms beyond it.
Basically this is a) to make the game refuse right away when we try to go somewhere not allowed, rather than walking halfway and then giving the refusal message, and b) to give the same refusal message no matter what room behind the "hindrance" we try to go to.
> Consistent go to-refusal messages

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Animal Actions and Human Conversation.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Character Models.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tests.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
- Counterfeit Monkey.materials/Extensions/Emily Short/Threaded Actions.i7x
- Counterfeit Monkey.materials/Extensions/Emily Short/Threaded Conversation.i7x
An attempt to speed up the conversation system, mainly by reducing the number of quips checked for availability each turn and changing the way parsing of things mentioned by quips work. Some more code from Chris Conley's later version of Threaded Conversation was also transplanted into ours.
It seems to be quite a bit faster, especially when asking about unimplemented things and typing other things that are not the suggested quips, such as TALK TO BARKER when first meeting him or ASK FARMER ABOUT YAM.
> New conversation

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act I Among Sightseers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act V Atlantida Herself.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Presentation Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tools.i7x
This goal here is to always have exactly one paragraph break before and one paragraph break after every "Achievement accomplished" message.
It adds an alternative way of announcing achievements with a line break before the message, and a couple of special cases. I'm sure there are still situations where this will break, but I haven't found any so far.
Note that the full-game achievements, such as "Alex Rosehip award for completing the game in easy mode," are never actually announced, for aesthetic reasons. This is old behavior that is not changed by this pull request.
> Nicer line breaks around achievement messages

- Counterfeit Monkey.materials/Extensions/Emily Short/Threaded Actions.i7x
- Counterfeit Monkey.materials/Extensions/Emily Short/Threaded Conversation.i7x
This seems to be more effective than descriptions like `let N be the list of available purchasing quips which mention the noun in quip-repository;`
> Loop through quip-repository in order to make lists of available quips

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act II Among Smugglers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Character Models.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
- Counterfeit Monkey.materials/Extensions/Emily Short/Threaded Conversation.i7x
Let's make the most complicated code in this game even more so. This is the result of careful profiling of different methods, and seems on average to give a good speed up without sacrificing functionality.
Mostly this concerns the fairly rare case when we explicitly start a new conversation with somebody. Usually the game does this automatically for us when we enter a room with a character in it, except with the desk attendant in the hostel and the farmer at Hesychius road. These two could cause quite long pauses if we began the conversation by typing something like ASK ABOUT YAM or ASK ATTENDANT ABOUT INTERNET, or it would simply give the error "We aren't talking to anyone."
This code introduces the predicted-interlocutor global variable, which is set in the presence of these two people, …
> New conversation speed hacks.

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act I Among Sightseers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act II Among Smugglers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act III Among Scholars.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act IV Among Policemen.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act V Atlantida Herself.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Animal Actions and Human Conversation.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Approaching Speedups.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Schedule and Time.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/custom speedups.i7x
- tools/regtest/CM-regtest-hard
- tools/regtest/regtest-hard.sh
- tools/regtest/regtest.sh
- tools/regtest/regtest2.sh
This will "teleport" the player along rather than generating going actions, unless the room moving to is marked as a "checkpoint". A checkpoint is basically a room behind some kind of door or barrier that we don't want the player to be able to sneak past. 
This PR contains code that makes sure that route-finding is never recalculated. Instead of asking for "the best way" we now ask for "the true-best way". Together these makes moving around much faster.
> New Approaching code

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act I Among Sightseers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act III Among Scholars.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Major Contents.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
- Counterfeit Monkey.materials/Extensions/Jim Aikin/Notepad.i7x
When I originally made this run on Inform 6M62, I couldn't get Notepad to accept the pen and the pens in its allowed-pens lists. In the end I just changed the list into a relation, with a penalty of increased memory usage and slower performance. It turns out it could be fixed by just moving the declaration of the pen and pens instead.
> Restore Notepad to its original glory.

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Multimedia.i7x
- Counterfeit Monkey.materials/Extensions/Emily Short/Glulx Entry Points.i7x
Small changes to fix #76 , see [my comments](https://github.com/i7/counterfeit-monkey/issues/76).
I'm not sure why HandleGlkEvent was commented out in the first place (in [3d67285](https://github.com/i7/extensions/commit/3d6728535c9637d5778d5e0d52d68f70938a3c36) ), so this might be bad in some way.
> Fix #76, graphic links not working.

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Multimedia.i7x
This adds a Before refreshing the graphics window rule that makes sure that the graphics window has the right proportions to show the entire map scaled to the full width of the graphics window.
Basically it first forces the width of the graphics window to half that of the total width of the parent game window (using a custom "force the percentage of (win - a g-window)" phrase), checks if this can accommodate the map, and if not, makes it narrower.
It is necessary to do it this way because Glk provides no way to directly get the width of the total game window in pixels.
This is tested on Gargoyle, Lectrote and Zoom.
The rule gets called four times every time the player adjusts the size of the window (but only two on Gargoyle for some reason), and I don't understand enough of Glk and …
> Make sure that the graphics window always has the right size. Fixes #80.

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act I Among Sightseers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Schedule and Time.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tests.i7x
- Counterfeit Monkey.materials/Extensions/Dannii Willis/Glk Object Recovery.i7x
This is a quick-and-dirty implementation of #97. In a debug build, the game will look for a file named "autotesting.glkdata" which contains the name of an in-game test, run the test and, if it reaches the end of the game, print out the time it took.
It has some problems with the initial questions but seems to work. The autotesting file will need to have the standard header: "* //7B5A779B-4653-43DB-A516-F475DDC12987// autotesting" and then the name of the test on the next line, e.g. "me".
Note that some interpreters will not understand the ".glkdata" suffix, and instead look for a file named just "autotesting".
Any present Counterfeit Monkey-startup-data.glkdata file will break things, and should be deleted before each run.
I first tried to reuse the "testing.glkdata" file for this, but …
> Non-interactive profiling mode

- Counterfeit Monkey.inform/Source/story.ni
The pause at startup is not very long any more, and I think it looks nicer without it. All functionality is still there.
> Hide Startup Precomputation startup message.

- Counterfeit Monkey.materials/Extensions/Dannii Willis/Ultra Undo.i7x
This small change was useful to make this game run on my Iphone (i.e. through [here](https://tass.neocities.org)). It also lowers the minimum number of save files.
> Implement switch to always use file-based undo.

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act IV Among Policemen.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Dispensers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Fakes.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Homonym Indices.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Initial Proffering.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Letter Hash Codes.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Liquids.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Major Contents.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tools.i7x
This makes the sap dispenser actually contain sap, which can be gelled back into soap. It also adds a sop dispenser, containing a sop, which likewise can be gelled back into soap. Furthermore, it restores the possibility to place a container on the sink (or the floor if no sink is available) in order to collect the liquid coming out of the dispenser. Includes some fixes to fluid handling.
> New dispensers functionality

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act II Among Smugglers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Animal Actions and Human Conversation.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tools.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
Allow the player (and the mechanic) to make a second car driveable. It is quite useless but does hopefully not break anything. I just couldn't come up with a good reason why the mechanic should refuse to fix a second car, when it is possible to get two cans of oil and two kinds of fuel.
The code that makes it impossible to create a car inside a container, such as another car, with the exception of the synthesizer, does perhaps not belong in this PR.
TODO:
> Allow fixing a second car

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
Adds some interaction between the roc and the boar, making it possible to avoid the attacking boar by creating or bringing along the roc.
> Boar-roc interaction

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Animal Actions and Human Conversation.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Repository Alphabetic Details.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Tests.i7x
The trap is actually not useful for anything, but the player might try to use it to stop Atlantida, the guards or the boar. This PR adds some responses to this.
> Responses to trying to use the trap

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Safety Overrides and Disasters.i7x
Was browsing recent commits and spotted these minor text errors:
* Mid-sentence double space in the description of the massive pug
* Incorrect reference to the "carp" transforming into the big revel instead of the big lever
> Fix a couple of typos in Disasters

- Counterfeit Monkey.inform/Source/story.ni
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act I Among Sightseers.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Multimedia.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Presentation Details.i7x
Show a full-window map with the new command MAP. Also renames GRAPHICS ON and GRAPHICS OFF to MAP ON and MAP OFF, respectively. Some new instructional messages are added as well.
> Add a full-screen map. Fixes #185 and #186

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
This MR fixes this funny bug:
> \>get in shower
> (getting off the toilet)
> You get into the shower.
> 
> \>turn on shower
> As we turn on the water, yourself washes down the drain.
> 
> *** Run-time problem P43: Attempt to remove the player from play.
(Of course, if escaping Atlantis were as easy as this, Alex would have tried it by now.)
You can even softlock yourself by entering a bath, dropping all, then turning on the bath!
> \>enter bath
> We get into the bath.
> 
> \>drop all
> *The Problem of Adjectives*: We put down *The Problem of Adjectives*.
> ring: We put down the ring.
> key: We put down the key.
> as: We put down the as.
> Origin Paste: We put down the Origin Paste.
> backpack: We put down the backpack.
> O-remover: We put down the O-remover.
> 
> \>exit bath
> We get out …
> Prevent shower drain softlock

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Animal Actions and Human Conversation.i7x
Currently, attempting to backtrack south through the tall window from the Precarious Perch can trigger a confirmation prompt.
This PR fixes that. Now the behavior is:
> \>s
> It's locked again. There's no way for you but forward from here.
This edits a pretty important rule, so I'd appreciate confirmation that I'm not breaking anything :)
> don't hesitate to try backtracking through the tall window

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act V Atlantida Herself.i7x
- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/World Model Tweaks.i7x
Currently, turning on the ebook reader yields this message:
> \>switch on ebook reader
> The ebook reader chimes cheerfully.
> 
> We can type search terms to look for data records.
That last line is the description of Book search. But Book search's description is declared as:
`The description of Book search is "There is a long, scrolling list of books, with titles on economics, biography, linguistics, and history. A search bubble allows the user to search for specific genres or titles."`
This description is nowhere to be found ingame due to the search engines rule:
```
When play begins (this is the search engines rule):
repeat with item running through search engines:
now the results-found response of item is "The search turns up the following results:";
now the description of the item is …
```
> Restore search engine descriptions

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Act V Atlantida Herself.i7x
The built-in seating at the galley table didn't allow sitting.
Before:
> \>sit on seating
> You can't sit on the seating.
Now:
> \>sit on seating
> You are now seated on the seating.
We can no longer *stand* on the seating, which makes sense to me. (I imagine the ceiling would [plausibly](https://yachtemoceans.com/wp-content/uploads/2020/01/Wally-Saudade-Sailing-Yacht-2.jpg) be too short for this, considering how cramped the rest of the yacht is.)
> Allow sitting on seating

- Counterfeit Monkey.materials/Extensions/Counterfeit Monkey/Animal Actions and Human Conversation.i7x
When adapting the code to Inform 6M62, I made this part a little less elegant. Basically it does the equivalent of setting a global variable instead of passing a variable as an argument. This should return it to its former glory.
> Make the origin paste wager closer to the original code
